name: load_media
description: "LoanMedia - GestiÃ³n de prÃ©stamos de equipos"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.10.3
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  uuid: ^4.5.2
  flutter_hooks: ^0.21.3+1

  go_router: ^10.1.2

  image_picker: ^1.2.1

  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/img/
